name: web_engine_tester

# Keep the SDK version range in sync with lib/web_ui/pubspec.yaml
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  js: 0.6.3
  stream_channel: 2.1.0
  test: 1.17.7
  webkit_inspection_protocol: 1.0.0
  ui:
    path: ../../lib/web_ui
